name: Cross Repo Trigger Test

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Trigger Workflow in Another Repository
          run: |
            REPO_OWNER="Revature" 
            REPO_NAME="cloud-ide"  
            EVENT_TYPE="trigger-workflow" 
            SERVICE="cloud-ide-proxy"
            VERSION="${{ github.sha }}"
            BRANCH="${{ github.ref_name }}"
    
            curl -L \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.API_PAT }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
              -d "{\"event_type\": \"$EVENT_TYPE\", \"client_payload\": {\"service\": \"$SERVICE\", \"version\": \"$VERSION\", \"branch\": \"$BRANCH\", \"unit\": false, \"integration\": true}}"